### ISSUE TITLE
Batch Translate API terminates on encountering the very first invalid text or text with just numbers

### ISSUE THREAD

**Issue by sshivprasad** [nidhaloff/deep-translator#108]
* deep_translator version: 1.5.4
* Python version: 3.8.8
* Operating System: Windows 10

### Description
When using batch translate in Google Translator, ran into an exception when the API encountered a text with only numbers. I think it would be better if in case of the batch API such an exception is handled and the input text is returned back, so that it proceeds to translate the next text in the list instead of terminating the script. 

The exception:

![image](https://user-images.githubusercontent.com/37325502/136564671-543ba733-550c-4718-b08e-6e5355724210.png)

**Comment by nidhaloff** [comment]
@sshivprasad Exactly, hence you want to adapt deep-translator for your use-case, which is not good because you can imagine how the package will look like if we adapt it to every user's use-case. Therefore, you need to find a way to do this ;) 

Why is filtering rows before passing it to the translator difficult? how it would be difficult to map it to the right index? if you show me an example, maybe I can give you an idea.
