### ISSUE TITLE
Error with proxies

### ISSUE THREAD

**Issue by LeMoussel** [nidhaloff/deep-translator#110]
* deep_translator version: v1.5.4
* Python version: 3.7
* Operating System: Windows 10

### Description
With [Proxy usage](https://github.com/nidhaloff/deep-translator#proxy-usage) example & my own proxy, I got this error

```
Une exception s'est produite : ConnectionError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000022BED216E48>: Failed to establish a new connection: [WinError 10060] Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu'))
  File "C:\Users\H\AppData\Local\Programs\Python\Python37\Lib\site-packages\urllib3\connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\H\AppData\Local\Programs\Python\Python37\Lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\H\AppData\Local\Programs\Python\Python37\Lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
```
I suspect that this error is due to this in [constants.py](https://github.com/nidhaloff/deep-translator/blob/master/deep_translator/constants.py#L203)
`microsoft_languages_response = requests.get(microsoft_languages_api_url)`
=> This request is made without the use of proxies!

**Comment by nidhaloff** [comment]
Hi @LeMoussel can you paste your code? it's hard to tell what went wrong just by looking at your error. Generally, I tried and tested the use of proxies many times and I can say that it works fine. Which proxy are you using? can you give a reproducible example?

**Comment by martina-chlebcova-csob-sk** [comment]
Hello, I'm having the same issue. We are behind proxy at work. The problem here is that when importing the module deep-translator the proxy blocks the requests to "microsoft_languages_api_url".

Code:
from deep_translator import GoogleTranslator

Error: SSLError: HTTPSConnectionPool(host='api.cognitive.microsofttranslator.com', port=443): Max retries exceeded with url: /languages?api-version=3.0&scope=translation (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))

I believe it is related to this part in constants.py
    204 microsoft_languages_api_url = "https://api.cognitive.microsofttranslator.com/languages?api-version=3.0&scope=translation"
--> 205 microsoft_languages_response = requests.get(microsoft_languages_api_url)
    206 translation_dict = microsoft_languages_response.json()['translation']

My suggestion (that works for me) is to replace microsoft_languages_response = requests.get(microsoft_languages_api_url) with microsoft_languages_response = requests.get(microsoft_languages_api_url, **proxies=proxy_definition, headers=header_definition, verify=False** <-- because of SSL errors).

Info:
deep-translator==1.6.1
Python 3.7.10
jupyter-notebook : 6.0.3
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"

Thanks a lot.
Martina
