### ISSUE TITLE
Error with single_detection, from detection.py

### ISSUE THREAD

**Issue by ObedH26** [nidhaloff/deep-translator#114]
Hello, if anybody can light me its would be cool.

I just get this error too often when i want to detect a language.
I tried many way to code this but anyway its change nothing and no idea why , i checked the inside of detection.py and i dont get the things.

/var/mobile/Containers/Data/Application/6D56E86F-4BB6-431A-9742-152635F249DB/Library/lib/python3.9/site-packages/deep_translator/detection.py in single_detection(text, api_key, detailed, *args, **kwargs)
     55         return detections[0]
     56 
---> 57     lang = detections[0].get('language', None)
     58     if lang:
     59         return lang

IndexError: list index out of range

**Comment by nidhaloff** [comment]
Please open just one issue per topic. I noticed you already opened an issue for language detection. Let's discuss it there. I will close this issue.

As I commented for the other issue you opened, please provide what you did, your code or an example of what you tried, so that we can understand your problem and help you further.
