### ISSUE TITLE
Code improvement and new feature

### ISSUE THREAD

**Issue by Vincent-Stragier** [nidhaloff/deep-translator#129]
Hi,

I was wondering if wrapping the translator would be more efficient in some situations. So I tried the following:

```Python
import deep_translator


def generate_engines_dict() -> dict:
    base_translator_type = type(deep_translator.parent.BaseTranslator)

    def is_translator(_object: str, __object: object) -> bool:
        # Need consistency in the names and in the code
        # (all translators do not depends on the class BaseTranslator)
        return (
            isinstance(__object, base_translator_type) or
            _object.endswith('Translator') or
            _object == 'DeepL' or
            _object == 'QCRI'
        )

    translation_engines = {}
    for _object in deep_translator.__all__:
        __object = getattr(deep_translator, _object)
        key_name = _object.replace('Translator', '').lower()
        if is_translator(_object, __object):
            translation_engines.update({
                key_name: getattr(deep_translator, _object)
            })
    return translation_engines


translation_engines = generate_engines_dict()


def engine(
    engine_name: str, *args, **kwargs
) -> deep_translator.parent.BaseTranslator:
    try:
        return translation_engines[engine_name.lower()](*args, **kwargs)
    except KeyError:
        keys = '\', \''.join(translation_engines.keys())
        raise(KeyError(f'Please provide a valid engine name (\'{keys}\')'))


text = 'Salut les amis :-)'
print(engine('libre', source='fr', target='en').translate(text))

# translated = GoogleTranslator(
#     source='auto', target='en').translate(text=text)
# print(f"{translated}")
```

It seems easier to switch from an engine to another, but it also highlights some inconsistencies in the code. All the translators are not all ending with `Translator` in their name, and the same goes for the inheritance of the `BaseTranslator` class.

**Comment by nidhaloff** [comment]
Hi @2010019970909, yes there are indeed some inconsistencies in the code despite my efforts to keep it as consistent as possible when I started coding it. This is because each translator has different requirements and relies on different interfaces. For instance, deep-translator uses API keys or the "official" API for DeepL, on the other hand, it uses web scraping to scrap google translations. Therefore, not all translator classes inherit from BaseTranslator. 

BaseTranslator is the parent class of all translators that rely on web scraping. All others that rely on the official API cannot inherit from it (well theoretically they can, but I don't want that since this will mess up the separation logic). Furthermore, there are some special cases. For example, some translators like the PapagoTranslator needs a clientId and an API key to use the official API, therefore, the interface would be also different from DeepL. 

I'm open to improvements and new ideas of course. However, we need to keep in mind that not all translators have the same interface. For instance, in your code, you can easily switch the translation engine, but you should also know which parameters you need to provide for the particular translator in order to work with.

We can surely add an "Engine" class that hides these "inconsistencies" as you show in your code example, but users still need to figure out the parameters needed by the translator or rather the API used by the translator in the background. I'm open to suggestions

**Comment by 2010019970909** [comment]
In #130, I implemented another solution. We register all the non-inherited translators to the base class. It later simplifies the addition of new translation engines. Also, it allows removing the static dictionary used in the CLI (probably easier to maintain in the long term). And finally we initialize an engine function which will return the desired class when called.

Of course, it's not perfect, but we can use dictionaries to correctly initialize any engine.
