### ISSUE TITLE
Load multiple proxies from file

### ISSUE THREAD

**Issue by ItCameFr0mMars** [nidhaloff/deep-translator#137]
Hello, are multiple proxies supported? and how could I import them from a text file into the dict used?

**Comment by nidhaloff** [comment]
Hi, @ItCameFr0mMars yes multiple proxies are supported. You just need to pass them as a dict.

Reading a text file into a dict is not specific to deep-translator. Therefore the issue is not really related to the package. 
Just take a look at how you can read a text file and parse it into a json/dict in python. I'm sure there is a lot of examples, otherwise you can post your file here and we will try to help you further ;)

**Comment by ItCameFr0mMars** [comment]
I actually found proxies to have very little impact, how many requests would need to be made before one would be ratelimited?
