### ISSUE TITLE
Not translate some part of text?

### ISSUE THREAD

**Issue by NeuroinformaticaFBF** [nidhaloff/deep-translator#150]
* deep_translator version: 1.5.0
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Description

I need to perform the following operations:

I need to translate (from english to italian) a document that contains some tags. However, the tags themselves do NOT have to been translated.
#### Example:
Original english text
"Patient shows signs of ^entity type = DISEASE^ flu ^/entity^ today."
Translated italian text
"Il paziente mostra segni di ^entity type = DISEASE^ influenza ^/entity^ oggi."

Is it possible to perform such operation?
And if it is, how can I do it?

### What I Did
I found this [SO post](https://stackoverflow.com/questions/54154549/how-to-disable-google-translate-api-from-not-translating-proper-names-with-commo) but it doesn't help much.
Currently I'm passing the text to translator as a simple string.
I will some minimal code to show what I did.

```
from deep_translator import GoogleTranslator
translated = GoogleTranslator(source='auto', target='it').translate(text)
```

**Comment by nidhaloff** [comment]
@NeuroinformaticaFBF tbh, I didn't get what you mean. Can you provide an example with your expected output and the current one?

**Comment by NeuroinformaticaFBF** [comment]
> @NeuroinformaticaFBF tbh, I didn't get what you mean. Can you provide an example with your expected output and the current one?

I'm sorry, I posted an example with XML style tags but I didn't notice they were not printed.
I edited the original post by using ^entity type = ...^ ... ^/entity^ as tags.

Basically, I need to translate the whole text except the content of such tags.

A more realistic example:
Input --> Original english text:
"CVD risk factors (hypertension, high LDL **^/entity type = TRIVIAL ^**cholesterol**^/entity^**, low HDL **^/entity type = TRIVIAL ^**cholesterol**^/entity^**, high **^/entity type = FAMILY ^**triglycerides**^/entity^**, obesity) were measured at the time of diabetes diagnosis."
I need to NOT translate the characters in bold, so here my expected output (translated italian text):
"I fattori di rischio CVD (ipertensione, **^/entity type = TRIVIAL ^**colesterolo**^/entity^** LDL alto, **^/entity type = TRIVIAL ^**colesterolo**^/entity^** HDL basso, **^/entity type = FAMILY ^**trigliceridi**^/entity^** alti, obesità) sono stati misurati al momento della diagnosi di diabete."


I already tried to add tags in XML style because in some example it did not get translated, but sometimes it did, so I need a more reliable way to do that.

Hope it's more clear now

**Comment by nidhaloff** [comment]
@NeuroinformaticaFBF I see now what you mean. The thing is, deep-translator is only the middleman in this whole translation process. For instance, when you translate using Google Translate, deep-translate will just send your text to the Google Translate server, receive the response and give it back to you. 
Therefore, what you are asking is not possible using deep-translator. It does also not make much sense to build this "filtering" into deep-translator since it is not a translator per se. 

What you should do instead is to filter these tags, since you as a user know what you want to filter. You can write python code that filter these tags for you. For example if your text is something like "<tag>blabla</tag>", you can write python code that filters the <tag> and </tag>, then pass the blabla text to deep-translator for translation and at the end just wrap the translation between <tag> and </tag> again. This should be straightforward to do.

The deep-translator implementation should be kept simple and not take these rare cases into account, because it can easily get very complicated depending on the tags. Therefore, deep-translator should only act as a middleware to the "real" translator. Hope I answered your question
