### ISSUE TITLE
GoogleTranslator pauses after a certain number of lines

### ISSUE THREAD

**Issue by cherellej** [nidhaloff/deep-translator#163]
* deep_translator version: 1.8.3
* Python version: 3.10.6
* Operating System: MacOS Monterey

### Description

I have been trying to translate a bunch of files containing reviews by country. Translation works for smaller files (less than 1000 rows), however it gets stuck on bigger files. No error is thrown, it just doesn't go past a certain number of rows even if I run it overnight.

### What I Did

```
for f in files:
    df = pd.read_csv(f)
    freviews = df['review']
    treviews = []
    count = 0

    for line in freviews:

        try:
            result = GoogleTranslator(source='auto', target='en').translate(text=line)
            time.sleep(0.01)
            count += 1
            print(count)
                
        except Exception:
            print(count)
            print("!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            pass

        treviews.append(result)
        
    df['review'] = treviews
    df.to_csv(f, index = False, encoding='utf-8-sig')
```

In this instance, I attempted to translate a file containing 2883 rows. I found that after 25 mins, the program did not output after 1164. After 235 mins, there was no further output. Is this due to exceeding a certain number of requests/quota set by Google Translate? If so, how can I go around that other than setting `time.sleep()`?

**Comment by nidhaloff** [comment]
@cherellej sorry for the late reply, I was very busy.
It's really hard to tell what went wrong here without knowing what do you want to translate. Normally, if the number of requests exceeded the max, then deep-translator should break and give you a `TooManyRequests` error. In your case, it hangs or did not output as you said, so I'm not really sure what happened. 

What I can tell you is that adding a time.sleep would help, but not a millisecond because the google server will still notice the too many requests. Probably a second would help.

What I also noticed is that you are creating the translator inside a for loop. This is not a good idea. If you take a look at the docs, there is a description on how to re-use the translator object. So in other words, you can create the translator object outside the for loop. This will save you some computation time and lead to better performance. Hope this helps
