### ISSUE TITLE
Error using translate when deploy on Heroku

### ISSUE THREAD

**Issue by MarceloDiefenbach** [nidhaloff/deep-translator#215]
* deep_translator version: 1.11
* Python version: 3.9.13
* Operating System: Mac OS / Deploy on Heroku

### Description

I'm creating an API route using Python and Flask to translate some phrases. Everything is working locally, but when I deploy it to Heroku, I always get the following error: deep_translator.exceptions.TranslationNotFound: hello --> No translation was found using the current translator. Try another translator?

<img width="1184" alt="Captura de Tela 2023-05-27 às 12 25 12" src="https://github.com/nidhaloff/deep-translator/assets/58398373/6ae1f434-ff0b-4d1e-ac5a-ad8a74010988">

**Comment by nidhaloff** [comment]
Since it's working locally, this is probably not a deep-translator specific issue. I assume It is heroku specific. Maybe it has something to do with how heroku handles traffic. Since deep-translator is using web-scraping, it depends on the way the traffic is being handled by the server.

If you want, try to check if it works using the official [deep-translator-api](https://github.com/nidhaloff/deep-translator-api). You can test it on the UI [here](https://deep-translator-api.azurewebsites.net/docs) as well
