### ISSUE TITLE
update deep-translator's cli

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/deep-translator#22]
### Description

The cli functionality needs to be updated since more translators are now integrated. This is a fair easy issue for new comers to help people contribute to the project.

PS: consider using click https://click.palletsprojects.com/en/8.0.x/

**Comment by devrobgilb** [comment]
Is the fact that QCRI is not included in the cli related to this error that I got:

`from deep_translator import (QCRI)
>>> translated = QCRI("XXXXXXXXXXXXXXXXXXXXX").translate(source='en', target='ar', domain="news", text=text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/deep_translator/qcri.py", line 77, in translate
    translation = res["translatedText"]
KeyError: 'translatedText'`

**Comment by nidhaloff** [comment]
@devrobgilb No certainly not. Hmm this is interesting, I will check it out asap

**Comment by inancg** [comment]
Hey @nidhaloff I like using cli whenever I can. The projects excites me and would like to start contributing. 

Is this issue still open? If so, I would like to come back with some propositions and POC.

Best regards,
Inanc

**Comment by nidhaloff** [comment]
hey @inancg  thanks for joining. The issue is still open yes. Feel free to check it out and make a pull request or create an issue if you have new ideas

**Comment by bigsbunny** [comment]
Hey @nidhaloff ! Just came across this issue. This module seems interesting. Just wanted to know if this issue is still open and if I could I start contributing to it?

Thanks & Regards,
Bighnesh Sahoo

**Comment by nidhaloff** [comment]
@bigsbunny yeah sure, you can start working on it. Feel free to make a PR

**Comment by tuyenhn** [comment]
Hi @nidhaloff, I am interested in working on this issue and get more familiar with open-source, and this issue seems fairly easy enough for me.

**Comment by nidhaloff** [comment]
@tuyenhn Hi, sure thanks for joining. You can start working on this. You can consider using the click library if you are familiar with it https://click.palletsprojects.com/en/8.0.x/

**Comment by tuyenhn** [comment]
Hi @nidhaloff, it seems like all of the unimplemented translators (DeepL, QCRI, Yandex, Microsoft and Papago) requires API keys or something similar. Do you want me to also create an `--api-key` argument of some sort for those translators?
Besides that, I have refactored the cli into using the click library.

**Comment by nidhaloff** [comment]
@tuyenhn Awesome! thank you. Yes exactly, an `--api-key` is definitely needed in that case

**Comment by Duncanr-glitch** [comment]
I'm not sure if this will be fixed by any of those changes, but I was looking at this the last few days, and the main issue with the translate function seems to be a problem with the QCRI API for the issue that @devrobgilb mentioned: 

The 'translatedText' key is missing from the QCRI parameters found here: https://mt.qcri.org/api/v1/translate?parameters. 

If I run the QCRI class you made and replace 'translatedText' with 'success', I get: :TranslationNotFound: HELLO WORLD --> No translation was found using the current translator. Try another translator?" 

All of this combined, I don't think anything's wrong with your code, but that the QCRI API is broken for translation.

Maybe  I'm  missing  something, but that's what I've been able to gather,  this is also my first jab at open source contributions, so take it with a grain of salt.

**Comment by nidhaloff** [comment]
@Duncanr-glitch This is not the right place to discuss the issue. Can you please open an issue and explain how to reproduce it?
