### ISSUE TITLE
Translation Time

### ISSUE THREAD

**Issue by amindehnavi** [nidhaloff/deep-translator#258]
* deep_translator version: 1.11.4
* Python version: 3.10.12
* Operating System: Ubuntu

### Description

First, Thank you for your great work. My problem is about the varying time that it takes to translate a given text using `GoogleTranslation`. When I send the same text through your API for translation, most of the time, it takes sth bw 1 to 2 seconds, but in some situations, it may take about 6 to 10 seconds. I didn't find any problem with my internet connection or accessibility to `translate.google.com`, or in my code as well. Do you have any idea where the problem could come from, or what I need to include in my code?

Thank you

**Comment by nidhaloff** [comment]
@amindehnavi The package handles failure cases internally and tries to solve them automatically for you by trying different solutions. So for example, if something went wrong with the translation or the server didn't respond correctly, deep-translator will try to resend the request with different parameters. You can see this in the code as well, just check the translate function. I'm sure that's why there are some inconsistencies when it comes to translation time
