### ISSUE TITLE
Add tests for the cli 

### ISSUE THREAD

**Issue by nidhaloff** [nidhaloff/deep-translator#62]
### Description

The cli was re-written using the **click library**. However, there are no tests for the functionality of cli at the moment. 
Click offers great support for unit testing. [Read here](https://click.palletsprojects.com/en/8.0.x/testing/)

I will let this issue open for newcomers or anyone who is looking for a good first issue. I think this would be a great task for anyone who wants to join the project.

**Comment by tuyenhn** [comment]
My school semester just started, so, sadly I don't think I have time 😅

**Comment by nidhaloff** [comment]
@tuyenhn then I wish you success in school and keep coding ;)

**Comment by nothead31** [comment]
I am going through the Click documentation and learning how it works. I opened a branch for my changes so I can work from home and the office in my downtime.

**Comment by nothead31** [comment]
Is there a particular reason we are using Click instead of argparse @tuyenhn? From this section of Click's documentation, I don't see what benefit Click provides over argparse, which seems to be easier to maintain.

> Why not Argparse?
Click is internally based on optparse instead of argparse. This is an implementation detail that a user does not have to be concerned with. Click is not based on argparse because it has some behaviors that make handling arbitrary command line interfaces hard:
>
>argparse has built-in behavior to guess if something is an argument or an option. This becomes a problem when dealing with incomplete command lines; the behaviour becomes unpredictable without full knowledge of a command line. This goes against Click’s ambitions of dispatching to subparsers.
>
>argparse does not support disabling interspersed arguments. Without this feature, it’s not possible to safely implement Click’s nested parsing.

**Comment by tuyenhn** [comment]
Not particularly, no. @nidhaloff suggested it, so I implemented it simple as that :)

**Comment by nidhaloff** [comment]
@nothead31 I find click pretty easy to work with and more importantly to test. The disadvantages of argparse are actually pretty clear in the text you posted. Mainly, I wanted to use click because of the click group concept
