### ISSUE TITLE
Docs shows failing

### ISSUE THREAD

**Issue by nothead31** [nidhaloff/deep-translator#70]
I have to dig through the RTD site, but for some reason the current version of the documentation shows failing. I'm putting an Issue here to either remind myself to investigate or allow someone to come in and dig through it themselves. Most likely the docs for __main__.py just need correcting, but there could be more.

**Comment by nidhaloff** [comment]
@nothead31 I can tell you why is this happening. I'm importing the __version__ variable from deep_translator.__init__,py in the docs configurations under docs/conf.py. Check it [here](https://github.com/nidhaloff/deep-translator/blob/master/docs/conf.py)

I'm doing this in order to build the docs and always show the current version. I don't want to do this manually each time I bump the version. There are certainly other ways to do this. From what I see, you moved the declaration of __version__ in setup.cfg. Therefore, the line `import __version__ from deep_translator` is causing the issue while building the docs.

**Comment by nothead31** [comment]
Ill resolve it either tonight or tomorrow, tha ms for clarifying the problem. Most likely I'll restore __init__.py for now while i review alternatives.
