### ISSUE TITLE
Convert from setup_tools to poetry for build backend

### ISSUE THREAD

**Issue by nothead31** [nidhaloff/deep-translator#74]
What it says on the tin: convert the build backend to Poetry. I already have a working Poetry workflow in my own project, and can do the conversion easily in a new branch, all that will be needed before merging to master is either reconfiguring Travis or switching to another CI. I haven't done much research on the different CI options, but @nidhaloff mentioned GitHub Actions which may be viable.

**Comment by nothead31** [comment]
Added an initial commit on a new branch. It *will* fail travis. I also changed the conf.py for Sphinx to read the version number directly from pyproject.toml to try and centralize version numbers in one single place. Added toml to the dev-requirements to do the job since I don't know of a better way at the moment.

**Comment by nidhaloff** [comment]
@nothead31 I added github workflows, so now we will use GitHub actions instead of travis. I noticed that the CLI tests have been always ignored because of how the function name is written. In `test_cli.py`, you named the function results_test. However, test function should have **test_** as a prefix, not a suffix. I fixed that typo and now the cli tests are failing in both travis and github actions.

It would be great if you can check it out ;)

**Comment by nothead31** [comment]
Ill look at it and see whats failing and ill add the changes in after i finish the poetry conversion
