### ISSUE TITLE
Is this package production ready?

### ISSUE THREAD

**Issue by LostInDarkMath** [nidhaloff/deep-translator#94]
Hi there,
I checked out many different Python translation libraries, but all of them had some problems suddenly and stopped working. I think most of them used the Google API.

I need a translator which is ready for production usage. So my questions are:
1) How reliable is your package?
2) Which if these translator implementations is the most reliable?
3) Are there in constraints in terms for example request limits?

**Comment by nothead31** [comment]
Closing because not an issue. Please use the discussions feature in the future for questions.

But for your questions:
1. The package itself is stable and gets bugfixes as needed, about twice a month on average so far. If you discover a problem, please create a new issue, we typically respond within less than a week, often only a couple days.
2. If you are translating to/from English, then they all should work fine. Some languages like Russian or German have hiccups in certain translators, and those are the majority of bug reports we receive.
3. Request limits are set by the APIs themselves, so you would need to reference the documentation for the given translator. The app itself does currently impose a (quite generous) character limitation, although that may change in the future as new features are developed.

**Comment by LostInDarkMath** [comment]
Thanks for your fast answer! I've overlooked the discussion feature. Sry for that.

**Comment by nidhaloff** [comment]
Hi @LostInDarkMath I want to add a few points. I started this project for the same reason you mentioned above. You can read the README/docs to know more. 

deep-translator is different. It does not use the Google API that's why it should be more reliable than other packages (I'm not saying other packages are bad, but this is my experience with packages that use the Google API).

If you check the history of deep-translator, you will notice that we are regularly fixing bugs, adding interesting features, and generally maintaining the project well.
